<a href="https://colab.research.google.com/github/juliosdutra/ModelagemPPEQ1019/blob/main/RNA_exemplo_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Created on Wed Nov  4 10:57:20 2020

@author: Julio Dutra
"""

import numpy as  np
import matplotlib.pyplot as plt

#%% função de ativação e sua derivada
def logistica(x):
    return 1/(1+np.exp(-x))

def der_logistica(x):
    return x*(1-x)


#%% dados de treino
u_treino = np.array([[0,0,1],
                     [1,1,1],
                     [1,0,1],
                     [0,1,1]])

y_treino = np.array([[0,1,0,0]]).T


#%% Ajuste da rede

np.random.seed(2020)
n_treino, n_w =  u_treino.shape

weights = np.random.randn(n_w,1)
print('\n Começando com pesos sinápticos randômicos:')
print(weights)

tol = 1e-6
criterio = 100
n = 1
taxa = 5
Fobj = []

while criterio > tol:

    camada_entrada = u_treino

    y_hat = logistica( np.dot(camada_entrada,weights) )

    erro = y_treino - y_hat

    ajuste = -erro * der_logistica(y_hat)

    weights = weights - taxa*np.dot(camada_entrada.T,ajuste)

    criterio = 1/2*np.sum(erro**2)
    n = n + 1
    Fobj.append(criterio)


print('\n Pesos sinápticos após o treino: ')
print(weights)

print('\nSaídas após o treino: ')
print(y_hat)

#%% teste da rede
u_teste = np.array([[1,1,1]])
y_teste = logistica( np.dot(u_teste,weights) )
print('\n Saída estimada: ')
print(y_teste)


 Começando com pesos sinápticos randômicos:
[[-1.76884571]
 [ 0.07555227]
 [-1.1306297 ]]

 Pesos sinápticos após o treino: 
[[ 14.17621625]
 [ 14.17621625]
 [-21.34854948]]

Saídas após o treino: 
[[5.35110568e-10]
 [9.99092476e-01]
 [7.66941611e-04]
 [7.66941611e-04]]

 Saída estimada: 
[[0.99909248]]
